name: GitHub Actions test
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      # This action requires an unshallow working copy,
      # so the following prerequisites are necessary:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Deploy your application
      - uses: 47ng/actions-clever-cloud@v1.2.0
        env:
          CLEVER_TOKEN: ${{ secrets.CLEVER_TOKEN }}
          CLEVER_SECRET: ${{ secrets.CLEVER_SECRET }}
      - run: echo "🍏 This job's status is ${{ job.status }}."